import type { LibraryEntry, Movie, RankedMovie, RecommendationInput, ScoreEvidence } from '../movies/domain';
const moodRules: Record<RecommendationInput['mood'], { genres: string[]; keywords: string[]; label: string }> = {
 calm:{genres:['Drama','Animation','Documentary'],keywords:['gentle','slice of life','meditative'],label:'sakin tonuna'}, fun:{genres:['Comedy','Adventure','Animation'],keywords:['feel-good','buddy','family'],label:'eğlenceli ritmine'}, dark:{genres:['Crime','Horror','Thriller'],keywords:['noir','psychological','mystery'],label:'karanlık atmosferine'}, romantic:{genres:['Romance','Drama','Comedy'],keywords:['relationship','love'],label:'romantik tonuna'}, tense:{genres:['Thriller','Crime','Mystery','Action'],keywords:['suspense','survival'],label:'gerilim beklentine'}, thoughtful:{genres:['Drama','Science Fiction','Documentary'],keywords:['philosophy','identity','society'],label:'düşündürücü yapısına'} };
const durationRange: Record<RecommendationInput['duration'], [number,number]>={short:[1,105],normal:[90,145],long:[120,260]};
const attentionRules: Record<RecommendationInput['attention'],{genres:string[];label:string}>={easy:{genres:['Comedy','Adventure','Animation','Romance'],label:'kolay takip edilen anlatımına'},medium:{genres:['Drama','Crime','Thriller','Adventure'],label:'dengeli anlatım yoğunluğuna'},intense:{genres:['Drama','Mystery','Science Fiction','History'],label:'yoğun anlatımına'}};
const contextRules={alone:{genres:['Drama','Horror','Documentary','Mystery'],label:'tek başına izlemeye uygun oluşuna'},couple:{genres:['Romance','Drama','Comedy','Thriller'],label:'birlikte izlemeye uygun tonuna'},group:{genres:['Comedy','Adventure','Action','Animation'],label:'grup izlemeye uygun ritmine'}} as const;
function overlap(values:string[],expected:readonly string[]){const set=new Set(values.map(v=>v.toLowerCase()));return expected.filter(v=>set.has(v.toLowerCase())).length}
export function isEligible(movie:Movie,input:RecommendationInput,watched:ReadonlySet<number>){if(watched.has(movie.tmdbId)||!movie.title||!movie.overview||!movie.posterUrl||(movie.voteCount??0)<80)return false;const[min,max]=durationRange[input.duration];return movie.runtimeMinutes==null?input.duration==='normal':movie.runtimeMinutes>=min&&movie.runtimeMinutes<=max}
function quality(movie:Movie){const rating=Math.max(0,Math.min(10,movie.voteAverage??0));const confidence=Math.min(1,Math.log10(Math.max(10,movie.voteCount??0))/4);return Math.round(rating*confidence*2)}
export function scoreMovie(movie:Movie,input:RecommendationInput,library:LibraryEntry[]):RankedMovie{const evidence:ScoreEvidence[]=[];const mood=moodRules[input.mood];const moodHits=overlap(movie.genres,mood.genres)+overlap(movie.keywords,mood.keywords);if(moodHits)evidence.push({code:'mood',label:mood.label,points:Math.min(32,18+(moodHits-1)*7)});if(movie.runtimeMinutes!=null){const target=input.duration==='short'?95:input.duration==='normal'?120:165;evidence.push({code:'duration',label:`${movie.runtimeMinutes} dakikalık süresine`,points:Math.max(4,18-Math.round(Math.abs(movie.runtimeMinutes-target)/10))})}const attention=attentionRules[input.attention];if(overlap(movie.genres,attention.genres))evidence.push({code:'attention',label:attention.label,points:11});if(input.context){const c=contextRules[input.context];if(overlap(movie.genres,c.genres))evidence.push({code:'context',label:c.label,points:7})}const favorites=library.filter(e=>e.favorite||(e.rating??0)>=4).flatMap(e=>e.movie.genres);const taste=overlap(movie.genres,favorites);if(taste)evidence.push({code:'taste',label:'kütüphanendeki beğendiğin türlerle kesişmesine',points:Math.min(15,taste*5)});const q=quality(movie);if(q)evidence.push({code:'quality',label:'izleyici puanı ve oy güvenine',points:q});const score=evidence.reduce((s,e)=>s+e.points,0);const reasons=evidence.filter(e=>e.code!=='quality').sort((a,b)=>b.points-a.points).slice(0,3).map(e=>e.label);return{movie,score,evidence,explanation:reasons.length?`Bu filmi ${reasons.join(', ')} göre seçtik. Puan ve oy sayısı yalnızca güven sinyali olarak kullanıldı.`:'Bu film süre uygunluğu ile yeterli puan ve oy güvenini birlikte sağladığı için seçildi.'}}
export function rankMovies(movies:Movie[],input:RecommendationInput,library:LibraryEntry[],previous:ReadonlySet<number>=new Set()){const watched=new Set(library.filter(e=>e.watched).map(e=>e.movie.tmdbId));return movies.filter(m=>isEligible(m,input,watched)).map(m=>{const r=scoreMovie(m,input,library);return previous.has(m.tmdbId)?{...r,score:r.score-24,evidence:[...r.evidence,{code:'history' as const,label:'yakın zamanda gösterilmiş olmasına',points:-24}]}:r}).sort((a,b)=>b.score-a.score||(b.movie.voteCount??0)-(a.movie.voteCount??0)||a.movie.tmdbId-b.movie.tmdbId)}
